[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 15

[cursor]
style = { shape = "Beam" }
vi_mode_style = { shape = "Block" }

[keyboard]
bindings = [
  { key = "V", mods = "Control", action = "ToggleViMode" },
  { key = "PageUp", mods = "Alt", action = "ScrollPageUp" },
  { key = "PageDown", mods = "Alt", action = "ScrollPageDown" },
]

[window]
decorations = "Buttonless"
padding = { x = 10, y = 5 }

